# Generated by Django 4.1.7 on 2023-03-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('Administrador', 'Utilização das funções gerais do sistema')]},
        ),
    ]
